# Generated by Django 4.2.6 on 2023-10-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='style',
            new_name='style_id',
        ),
    ]
