# Generated by Django 4.2.7 on 2024-04-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('X', 'X'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('M 7', "Men's 7 / Women's 8.5"), ('M 7.5', "Men's 7.5 / Women's 9"), ('M 8', "Men's 8 / Women's 9.5"), ('M 8.5', "Men's 8.5 / Women's 10"), ('M 9', "Men's 9 / Women's 10.5"), ('M 9.5', "Men's 9.5 / Women's 11"), ('M 10', "Men's 10 / Women's 11.5"), ('M 10.5', "Men's 10.5 / Women's 12"), ('M 11', "Men's 11 / Women's 12.5"), ('M 11.5', "Men's 11.5 / Women's 13"), ('M 12', "Men's 12 / Women's 13.5"), ('M 12.5', "Men's 12.5 / Women's 14"), ('M 13', "Men's 13 / Women's 14.5"), ('M 14', "Men's 14 / Women's 15.5"), ('M 15', "Men's 15 / Women's 16.5"), ('M 16', "Men's 16 / Women's 17.5"), ('M 17', "Men's 17 / Women's 18.5"), ('M 18', "Men's 18 / Women's 19.5")], max_length=50, unique=True),
        ),
    ]
