# Generated by Django 4.2.6 on 2023-10-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('red', 'Red')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('X', 'X'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], max_length=50, unique=True),
        ),
    ]
