# Generated by Django 4.2.6 on 2023-10-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_style_style_style_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='name',
        ),
    ]
