# Generated by Django 4.2.6 on 2023-11-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_delete_productattribute'),
    ]

    operations = [
    ]
