# Generated by Django 4.2.6 on 2023-10-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_style_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='style_id',
            new_name='style',
        ),
    ]
